apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-dep-version
spec:
  description: This task can find out deprecated and removed kubernetes apiVersions
  workspaces:
    - name: source
      description: A workspace that contains fetched git repo.
  params:
    - name: manifest
      type: string
      description: path to manifest file or manifest directory
      default: "."
    - name: output
      type: string
      description: output format to use. (normal|wide|custom|json|yaml|markdown) (default "normal")
      default: "normal"
    - name : args
      type: array
      description: "args"
      default: []
  steps:
    - name: dep-version
      image:  quay.io/fairwinds/pluto:master
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
          
          result=
          if [[ -d $(params.manifest) ]]
          then 
            result=$(/pluto detect-files -d $(params.manifest) -o $(params.output) $*)
          else
            result=$(/pluto detect $(params.manifest) -o $(params.output) $*)
          fi

          if [ $? -eq 0 ]
          then
            echo "No deprecated or removed API versions found"
            exit 0
          else
            echo "$result"
            exit 1
          fi
      args:
      - $(params.args)